### ISSUE TITLE
xfxEntry problem with ReturnType

### ISSUE THREAD

**Issue by RafaelVieira2323** [XamFormsExtended/Xfx.Controls#89]
Please fill out either the bug or feature request section and remove whatever section you are not using.

# Bug 

* Version Number of Control: 1.1.3
* Device Tested On: xiaomi redmi note 3
* Simulator Tested On: Iphone x

### Affects

- [x ] iOS
- [ x] Android

### Expected Behavior
 Keyboard with button next

### Actual Behavior
Keyboard with button Done

### Link to Github Reproduction (optional but recommended)

[Repro]()

# Feature Request:
Please fill in what you would like

**Comment by eamiguinho** [comment]
If you look at the source code it's forcing to be DONE instead of taking the returntype we set, so you might need to just fork and do your own control I'm afraid, should be easy fix but maybe people are not supporting this anymore

**Comment by RafaelVieira2323** [comment]
I've been looking at the source code but I have not found the forcing of the DONE in returnType.

Can you tell me where you saw it? So I try to do something. And why are you forcing Done?

**Comment by eamiguinho** [comment]
Don't get me wrong mate, I never did any work for this controls I just found it with a search through the code because I'm having the same issue as you, here have a look:

https://github.com/XamFormsExtended/Xfx.Controls/blob/master/src/Xfx.Controls.Droid/Renderers/XfxEntryRendererDroid.cs#L114

They set it directly to Done in this line.

**Comment by ChaseFlorell** [comment]
When I built this, `Done` was the default behavior for Entry, so I just copied it. Has Forms allowed us to modify it now? If so, let's update to match! I will accept a PR, or do it when I have time (could take a while)

**Comment by eamiguinho** [comment]
Yeah you can do ReturnType="Done".

Docs: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry#customizing-the-return-key 

We might need to update XamForms to be able to do this, what version you have at the moment? I can make the request later today / tomorrow morning.

Thanks @ChaseFlorell

**Comment by RafaelVieira2323** [comment]
version of xfx.controls 1.1.3 e xamarin.forms 3.4.0.1008975

**Comment by eamiguinho** [comment]
@ChaseFlorell 

I did a quick update, have a look at my PR feel free to change anything or request me to change something.

https://github.com/XamFormsExtended/Xfx.Controls/pull/90

Thanks, Mani

**Comment by ChaseFlorell** [comment]
Great work @eamiguinho, thanks!

**Comment by eamiguinho** [comment]
Are you gonna update the Nuget package? @ChaseFlorell I didn't have much time to test, all looked good to you?

**Comment by ChaseFlorell** [comment]
everything looked good. I'll try to get one built by the weekend and upload as pre-release

**Comment by eamiguinho** [comment]
Great mate 👍

**Comment by RafaelVieira2323** [comment]
@eamiguinho  @ChaseFlorell Thank you for your help :).

**Comment by RafaelVieira2323** [comment]
i will test the new nuget, if have some problem, i will reporting you ;)

**Comment by eamiguinho** [comment]
Mate, I saw that you updated and I did update the nuget and now it's not even showing, can you please have a look? I followed your code pattern but maybe something went wrong with updating Xam.Forms so many versions ahead. Can you please test it and have a look?

**Comment by ChaseFlorell** [comment]
Hey @eamiguinho I did find a few issues that crept in after closing the PR's, I've not seen what you're describing though, could you please tell me exactly what you're experiencing and on which platform?

**Comment by ChaseFlorell** [comment]
I just pushed 1.2.1, please see if that yields better results.

**Comment by eamiguinho** [comment]
Hey @ChaseFlorell 

Yes, it shows now but I still have issues, some logs:

`[TextInputLayout] EditText added is not a TextInputEditText. Please switch to using that class instead.
[XfxEntryRendererDroid] Swallowing NoSuchFieldException - defaultHintTextColor.
[XfxEntryRendererDroid] Swallowing NoSuchFieldException - focusedTextColor.`

And it crashes when trying to give focus to an Xfx.Entry, exception:

`java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!`

maybe here?

`public bool OnEditorAction(TextView v, ImeAction actionId, KeyEvent e)
        {
            if (Element == null || Control == null || Control.Handle == IntPtr.Zero || EditText == null || EditText.Handle == IntPtr.Zero)
                return false;

            if ((actionId == ImeAction.Done) || ((actionId == ImeAction.ImeNull) && (e.KeyCode == Keycode.Enter)))
            {
                Control.ClearFocus();
                HideKeyboard();
                ((IEntryController)Element).SendCompleted();
            }

            return true;
        }
`

Maybe you need to add other ImeAction than just Done now? 

Sorry to bother you with this just trying to help.

**Comment by eamiguinho** [comment]
Btw I didn't test iOS yet, just Android, the crash I can't reproduce it anymore, but the action button is not working properly if not set to Done

**Comment by RafaelVieira2323** [comment]
I test in ios emulator, is working very well. I have a little problem in android, one entry dont lose focus.
The return type of my username entry is "next".

My code:
usernameEntry.Completed += (object sender, EventArgs e) => {
                usernameEntry.Unfocus();
                passwordEntry.Focus();
            };

**Comment by eamiguinho** [comment]
@RafaelVieira2323 yes, that's because it's only doing this if actionId == ImeAction.Done, needs to be added logic if ImeAction.Next to focus the next control and sendcompleted(), @ChaseFlorell I think this change is relatively small and quick to do, but today I'm away if you could implement that would be great (check iOS as well) 

`if ((actionId == ImeAction.Done) || ((actionId == ImeAction.ImeNull) && (e.KeyCode == Keycode.Enter)))
        {
            Control.ClearFocus();
            HideKeyboard();
            ((IEntryController)Element).SendCompleted();
        }`

**Comment by RafaelVieira2323** [comment]
@eamiguinho your solution is working. I'm going to pute the code here for @ChaseFlorell , you can use it to update the nuget.

public bool OnEditorAction(TextView v, ImeAction actionId, KeyEvent e)  
        {
            if (Element == null || Control == null || Control.Handle == IntPtr.Zero || EditText == null || EditText.Handle == IntPtr.Zero)
                return false;

            if ((actionId == ImeAction.Done) || ((actionId == ImeAction.ImeNull) && (e.KeyCode == Keycode.Enter) || (actionId == ImeAction.Next)))
            {
                Control.ClearFocus();
                HideKeyboard();
                ((IEntryController)Element).SendCompleted();
            }

            return true;
        }

**Comment by eamiguinho** [comment]
@ChaseFlorell https://github.com/XamFormsExtended/Xfx.Controls/pull/91 made the change to do it for any ImeAction on Android (iOS is working just fine). Can you please merge and release a new nuget update with this change? 

Best,
Mani

**Comment by RafaelVieira2323** [comment]
@ChaseFlorell  release a new nuget update with the new merge of @eamiguinho.

**Comment by ChaseFlorell** [comment]
@RafaelVieira2323 I don't take kindly to demands. I'll merge it once I have a minute to look at it, which is typically Saturday/Sunday.

**Comment by RafaelVieira2323** [comment]
@ChaseFlorell  it is not a requirement.

I wanted to ask if you could update the nuget.

**Comment by eamiguinho** [comment]
Hi @ChaseFlorell 

You had any time to have a look and create a NuGet update? 

Thanks a lot and sorry for asking again.

Mani

**Comment by RafaelVieira2323** [comment]
Hi @ChaseFlorell 

When you can, take a look and update Nuget.

'm sorry for always asking. And thank you.
